language: rust
rust:
  - stable
  - beta
  - nightly

cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

script:
  - cargo build

os:
  - linux
  - osx

notifications:
  email:
    on_success: never

branches:
  only:
    - master
