[package]
name = "chromecast-link-tool"
version = "0.3.0"
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]

[dependencies]
ansi_term = "0.7.5"
chromecast_link = { git = "https://github.com/azasypkin/chromecast-link.git", branch = "master" }
docopt = "0.6.81"
env_logger = "0.3.3"
log = "0.3.6"
rustc-serialize = "0.3.19"
